import { PUBLIC_TIER_RULES } from "./publicTierPolicy.js";
import type { MethodologyData, SourceTier } from "./types";
import {
  singaporeCity,
  bangkokCity,
  workedExample,
  workedExampleDisplayName,
  workedExampleDiRaw,
  workedExampleSafetyFormula,
  workedExamplePressureFormula,
  workedExampleMeanFormula,
  workedExampleAmpiFormula,
  formatOneDecimal,
  formatTwoDecimals,
  formatThreeDecimals,
  officialSlicFormula,
  officialAmpiFormula,
  growthPillarFormula,
  toleranceCompositeFormula,
  economicVitalityFormula,
  methodologyReferences,
  worksheetColumns,
  alphaCountryExclusionList,
  alphaCityExclusionList,
  maxJapanCrossTier,
} from "./methodologyShared";

export const koreanTierProtocolRule =
  `공개 순위는 정확한 비반올림 SLIC 점수 순서로 먼저 결정되며, Alpha·Beta·Gamma는 순위 이후에 별도로 적용되는 공개 오버레이입니다. 순위 번호 안에 지리적 필터가 숨겨져 있지 않습니다. ` +
  `공개 층 오버레이는 세 층 전체에 걸쳐 국가당 한 도시를 원칙으로 하되, 현행 프로토콜에서 대만은 ${PUBLIC_TIER_RULES.maxTaiwanAcrossPublicTiers}개 공개 층 슬롯을, 일본은 ${maxJapanCrossTier}개 슬롯을 보유할 수 있습니다. Alpha는 Community >= ${PUBLIC_TIER_RULES.alphaMinCommunity}, Pressure >= ${PUBLIC_TIER_RULES.alphaMinPressure}, 커버리지 등급 ${PUBLIC_TIER_RULES.alphaMinCoverageGrade} 이상을 요구하며, 누락된 압력 데이터는 최고 등급 주장으로 전환될 수 없습니다. 유럽은 Alpha에서 최대 ${PUBLIC_TIER_RULES.maxEuropeInAlpha}석, 오세아니아 ${PUBLIC_TIER_RULES.maxOceaniaInAlpha}석, 한국 ${PUBLIC_TIER_RULES.maxSouthKoreaInAlpha}석, 일본 ${PUBLIC_TIER_RULES.maxJapanInAlpha}석으로 제한됩니다. ${alphaCountryExclusionList}는 국가 규칙에 따라 Alpha에서 제외되며, ${alphaCityExclusionList}는 편집 생활비 규칙에 따라 Alpha에서 제외됩니다. ` +
  `Beta는 동일한 국가 규칙과 대만·일본 예외를 유지하면서 Community >= ${PUBLIC_TIER_RULES.betaMinCommunity}와 Pressure >= ${PUBLIC_TIER_RULES.betaMinPressure}로 거주 적합성 하한선을 높입니다. Gamma는 나머지 순위 도시들로 채워집니다.`;

export const koreanSingaporeRule =
  singaporeCity && bangkokCity
    ? `싱가포르의 현재 순수 점수 순위는 ${singaporeCity.rank}위이며, SLIC 점수는 ${formatOneDecimal(singaporeCity.slicScore)}, 커버리지는 ${singaporeCity.coverageGrade}이지만 공개 층 오버레이는 싱가포르를 ${singaporeCity.tierLabel ?? "공개 층 외부"}에 배치합니다. ` +
      `Viability(${formatOneDecimal(singaporeCity.viabilityScore)})와 Capability(${formatOneDecimal(singaporeCity.capabilityScore)})는 여전히 뛰어나지만, Community(${formatOneDecimal(singaporeCity.communityScore)})는 Alpha 하한 ${PUBLIC_TIER_RULES.alphaMinCommunity}과 Beta 하한 ${PUBLIC_TIER_RULES.betaMinCommunity} 모두를 밑돌며, Pressure(${formatOneDecimal(singaporeCity.pressureScore)})는 Alpha 기준은 충족하지만 Beta 기준은 충족하지 못합니다. ` +
      `방콕은 반대 결과를 보여줍니다. 순수 점수 순위 ${bangkokCity.rank}위에 SLIC ${formatOneDecimal(bangkokCity.slicScore)}이지만, Community(${formatOneDecimal(bangkokCity.communityScore)})와 Pressure(${formatOneDecimal(bangkokCity.pressureScore)}) 모두 Alpha 기준을 충족하고, 더 높은 순위의 태국 도시가 태국의 공개 층 자리를 먼저 차지하지 않았기 때문에 ${bangkokCity.tierLabel ?? "공개 층"}에 진입합니다. 독립적인 여행 비용 출처는 방콕의 공개 가치 제안을 뒷받침하지만, 이는 맥락적 증거이지 관광 감당 가능성 보너스 점수가 아닙니다.`
    : "이 페이지는 실시간 공개 데이터셋에 싱가포르와 방콕의 현재 행이 있을 때만 두 도시를 인용합니다.";

export const koreanSourceTiers: SourceTier[] = [
  {
    tier: "1등급",
    title: "도시·대도시권 공식 데이터",
    description: "오픈데이터 포털, 공공요금 규제기관, 교통 데이터 피드, 병원 공개 자료 및 도시 통계 기관.",
  },
  {
    tier: "2등급",
    title: "주·도·광역 공식 데이터",
    description: "지역 통계 기관, 대도시권 관측소 및 광역 행정 데이터셋.",
  },
  {
    tier: "3등급",
    title: "국가·국제 공식 데이터셋",
    description: "World Bank, WHO, ILO, UNESCO UIS, OECD, WIPO 및 WHO/UNICEF JMP.",
  },
  {
    tier: "4등급",
    title: "검증된 2차 및 실험적 레이어 데이터",
    description: "OpenAQ, Copernicus CAMS, Sentinel-2 / Sentinel-5P 맥락 레이어, JAXA 토지 제품, Landsat 파생 식생 레이어, M-Lab, 소셜 리스닝, 크라우드소싱 생활비 레이어, 그리고 명시적 주의사항이 포함된 도시 증언.",
  },
  {
    tier: "5등급",
    title: "분석가 평가 및 교차 검증",
    description: "실제 경험, 교차 검증 연구, 전문 지식을 바탕으로 한 SLIC 분석가의 수작업 평가. 관용성, 환대, 문화적 생활, 그리고 순수 데이터 수집이 어려운 정성적 신호에 활용됩니다.",
  },
];

export const methodologyDataKo: MethodologyData = {
  hero: {
    eyebrow: "방법론 보고서",
    title: "SLIC 방법론",
    strapline: "V3: 수치들이 어떻게 산출되는지 보여주는 진단 모델.",
    intro: "V1은 부산을 1위에 올려놓은 단순 스프레드시트였습니다. V2는 타이베이 무대에서 발표되어 여러 도시 지도자들에게 '우리 도시도 이렇게 분석해 줄 수 있느냐'는 질문을 이끌어냈습니다. V3는 측정 로직을 더욱 정교하게 다듬었습니다. 이제 모든 수치는 명시된 입력값과 직접 연계되고, 점수화된 항목은 눈에 보이는 진단 지표와 분리되며, 부문 간 불균형은 AMPI를 통해 명시적으로 페널티를 받습니다. 또한 워크벤치를 통해 독자들이 공표된 순위와 혼동하지 않고 다양한 가중치를 시험해볼 수 있도록 했습니다. 모델은 공개되어 있으며 공식은 선언되어 있습니다. 모든 도시의 수치는 검증 가능합니다.",
    doctrineTitle: "V3 원칙",
    doctrineBody: "SLIC는 도시를 단순한 브랜드나 대차대조표가 아닌, 살아 숨 쉬는 유기적 시스템으로 다룹니다. 이 모델은 가용성, 안전, 문화 및 공공 생활, 관용성, 성장 여건, 그리고 사람들이 실제로 누릴 수 있는 생활 공간을 추적합니다.",
    contextTitle: "국가 맥락 입력값",
    contextItems: [
      "1인당 GDP (PPP)",
      "GDP 성장률",
      "지니 계수",
      "사용자 지정 세율",
      "PPP 민간 소비 계수",
    ],
    explicitTitle: "공개 공식이 명시하는 바",
    explicitItems: [
      "안전은 감시의 강도가 아닌 실제 결과로 평가됩니다.",
      "관용성은 마찰 없는 공존과 동등한 시장 접근성을 통해 평가됩니다.",
      "비즈니스 활력은 명시적으로 점수화되며, 거시적 맥락은 보이지 않게 지배하는 대신 투명하게 통제된 지표로만 표시됩니다.",
    ],
  },
  readerGuide: {
    eyebrow: "독자 가이드",
    title: "대중에게는 가독성을, 분석가에게는 재현성을",
    summary: "이 방법론은 평이한 언어로 논지를 파악하려는 대중과 자신만의 도시 유니버스에 대한 점수를 계산해보고자 하는 분석가라는 두 부류의 독자를 동시에 만족시켜야 합니다.",
    layTitle: "쉬운 언어로 읽는 경로",
    technicalTitle: "기술적 복제 경로",
    laySteps: [
      "다섯 가지 지조(Pillars)를 다섯 가지 공공의 질문으로 이해하십시오: 감당 가능성, 일상적 생존력, 역량, 귀속감, 그리고 창의적/경제적 모멘텀.",
      "기술은 지원 수단으로 취급하십시오. 기술은 측정 가능한 일상 여건을 개선할 때만 의미가 있습니다.",
      "고비용 도시는 그에 따른 삶의 압박 항목과 함께 읽으십시오. 기관의 우수성이 주거나 시간 압박을 지워주지는 못합니다.",
      "중소 도시는 동일하게 선언된 기준선을 적용해 읽으십시오. 덜 주목받는다고 해서 측정 대상에서 제외되는 것은 아닙니다.",
    ],
    technicalSteps: [
      "도시를 기능적 도시 지역(FUA) 또는 합리적으로 획정할 수 있는 대도시권 단위로 정의합니다.",
      "도시 데이터를 최우선으로 수집하고, 그 다음 광역, 마지막으로 국가 대체 데이터를 적용하며 각 지표의 소스 등급(Source tier)을 기록합니다.",
      "점수를 매기기 전에 세금 조정을 거친 PPP 가용 생활 공간을 계산합니다. 단순 급여 수준만으로는 충분하지 않습니다.",
      "하위 5% 및 상위 95% 백분위수에서 윈저화(Winsorization)를 시행하고, 0-100으로 표준화하며, 해로운 지표는 역산하고, 점수화된 지표와 표시용 진단 지표를 분리하며, 순위와 함께 커버리지 등급을 공표합니다.",
    ],
  },
  critiqueSection: {
    eyebrow: "기존 순위의 한계",
    title: "SLIC가 해결하고자 하는 격차",
    summary: "기존의 도시 지수들도 참고할 만하지만, 상당수는 SLIC가 선언한 측정 기준과는 다른 도시 이론을 내포하고 있습니다.",
  },
  critiques: [
    {
      title: "명성이 종종 살기 좋은 여건으로 오인됩니다",
      body: "많은 순위들이 제도적 세련미, 재정 지출, 브랜드 인지도에 가산점을 줌으로써 이미 부유하고 격식화된 도시들을 구조적으로 우대합니다.",
      implication: "SLIC는 실제 체감되는 생존력과 도시의 명성을 구분하고, 1인당 GDP를 결정적 요소가 아닌 맥락 지표로 취급합니다.",
      citations: [1, 2, 14],
    },
    {
      title: "데이터 부족으로 인해 평가절하된 도시들이 산출 전에 누락됩니다",
      body: "중소 도시들은 벤치마킹 구조가 입수하기 쉬운 기존 데이터셋을 보유한 도시만을 수용하기 때문에 제외되는 경우가 많습니다.",
      implication: "SLIC는 감시 대상을 유지하고 커버리지 등급을 공표하며, 조용히 도시를 제외하는 대신 눈에 보이는 소스 사다리를 활용합니다.",
      citations: [1, 14, 15],
    },
    {
      title: "안전성이 스마트 기기의 존재 여부로 추정되곤 합니다",
      body: "앱, 대시보드, 감시 카메라 같은 하드웨어는 눈에 잘 띄지만 정작 시민들이 체감하는 도시는 안전하지 않거나 강압적일 수 있습니다.",
      implication: "SLIC는 실제 범죄 피해와 일상적 안전 체감도를 직접 점수화합니다. 카메라는 그 자체만으로 점수를 얻지 못합니다.",
      citations: [1, 11, 13],
    },
    {
      title: "생활 압박이 과소평가되는 경향이 있습니다",
      body: "필수 지출을 제외한 가용 소득, 가계 부채, 근로 시간, 자살률 등은 실제 도시 생활의 핵심이지만 부차적이거나 아예 배제되는 경우가 많습니다.",
      implication: "SLIC는 생활 압박과 여유 공간에 독자적이고 온전한 공식 가중치를 부여합니다.",
      citations: [1, 2, 3, 7],
    },
    {
      title: "관광객 수는 참고 정보일 뿐 자동으로 좋은 것은 아닙니다",
      body: "과도한 관광객은 체증, 범죄 또는 지역 커뮤니티의 환경 악화와 공존할 수 있습니다.",
      implication: "SLIC는 관광 수요를 맥락적 문화 수요 신호로 활용하되, 반드시 안전, 생태, 시민 사회의 압박 요인 검증을 통과하도록 설계했습니다.",
      citations: [1],
    },
  ],
  processSection: {
    eyebrow: "방법론 검증",
    title: "회의실, 패널, 워크숍에서 진행된 모델 스트레스 테스트",
    summary: "SLIC는 일회성 스프레드시트가 아닙니다. 이 프레임워크는 공표된 공식으로 확정되기 전까지 라이브 세션에서 반복적으로 설명되고, 도전받고, 개정되었습니다.",
    figures: [
      {
        id: "process-stage-ko",
        src: "/photos/report-people-stage.jpg",
        alt: "공공 도시 행사 중에 무대 위에 서 있는 사람들.",
        caption: "프레임워크는 사적 초안 작성을 넘어 공개적인 발표와 검증 과정에서도 살아남아야 했습니다.",
        width: 1440,
        height: 1440,
      },
      {
        id: "process-meeting-ko",
        src: "/photos/report-people-meeting.jpg",
        alt: "노트북과 마이크가 놓인 테이블 주변에 모여 회의를 하는 참석자들.",
        caption: "가정들은 데이터 선택과 도시 논리를 옹호해야 하는 실무 회의에서 정밀하게 검증되었습니다.",
        width: 1439,
        height: 1085,
      },
      {
        id: "process-workshop-ko",
        src: "/photos/report-people-workshop.jpg",
        alt: "착석한 청중에게 프레젠테이션을 하는 강사가 있는 워크숍.",
        caption: "파일럿 토론은 보기만 좋은 지표와 도시 생활을 실제로 설명할 수 있는 지표를 구분하는 데 도움이 되었습니다.",
        width: 2048,
        height: 1365,
      },
    ],
  },
  flowSection: {
    eyebrow: "점수 계산 흐름",
    title: "원시 지표가 공개 SLIC 점수가 되는 과정",
    summary: "점수 계산의 흐름은 고의적으로 짧고 검증 가능하도록 설계되었습니다: 원시 메트릭, 표준화된 메트릭 점수, 지조별 합산, 그리고 최종 가중 점수.",
    stages: [
      {
        id: "raw-ko",
        title: "원시 지표",
        body: "투명한 소스 등급과 함께 도시, 대도시권, 광역 및 국가의 신호를 수집합니다.",
        formula: "x_m(c)",
      },
      {
        id: "normalized-ko",
        title: "표준화",
        body: "하위 5% 및 상위 95% 백분위수에서 윈저화를 거치고 0-100 범위로 변환하며, 유해 변수는 역산합니다.",
        formula: "s_m(c)",
      },
      {
        id: "pillars-ko",
        title: "지조별 합산",
        body: "선언된 내부 가중치에 따라 메트릭 점수를 공개 지조별로 병합합니다.",
        formula: "P_p(c) = Sum observed alpha_(p,m) x s_m(c) / Sum observed alpha_(p,m)",
      },
      {
        id: "final-ko",
        title: "최종 점수",
        body: "고정된 단일 공개 방정식을 적용하고 커버리지 등급을 부여합니다.",
        formula: "SLIC(c)",
      },
    ],
  },
  remoteSensingSection: {
    eyebrow: "원격 탐사 레이어",
    title: "지상 센서가 너무 드물 때 도시 프레임을 확장하는 위성 증거",
    summary: "SLIC는 지상 관측소가 너무 적거나 국지적이며 불균일하여 대기질이나 생태적 경계를 온전히 설명하지 못할 때, 공간적 커버리지를 보완하기 위해 원격 탐사를 활용합니다. 위성 레이어는 마법 같은 진실이 아닌 보조적 증거입니다.",
    quantifyTitle: "위성 레이어가 정량화에 기여하는 부분",
    quantifyItems: [
      "광역 도시 대기권 내 에어로졸 부하 및 대기 조성",
      "NDVI 스타일의 토지 환경 정보를 통한 식생 및 녹지 버퍼링",
      "밀집된 건물 형태 주변의 지표면 덮개, 수분 및 지표면 맥락",
      "로컬 측정망이 누락할 수 있는 광역적 오염 이동 추적",
    ],
    qualifyTitle: "분석가가 정성적으로 해석해야 하는 부분",
    qualifyItems: [
      "지형, 해안선, 풍향, 계절성 연기 이동 경로",
      "국지적 핫스팟과 도시 전체 환경 여건의 차이",
      "도시의 조밀성, 가로 협곡(Street Canyon), 주민이 실제로 겪는 노출 빈도",
      "공식 환경 기록, 주민 증언 및 도시 내 지상 검증자료",
    ],
    workflowTitle: "위성 레이어가 방법론에 반영되는 단계",
    workflowStages: [
      {
        id: "remote-official-ko",
        title: "공식 도시 및 환경 기록",
        body: "지상 센서, 수도/전력 보고서, 대기질 측정값 등은 자료가 수집될 때 최우선 기본 레이어로 남습니다.",
      },
      {
        id: "remote-context-ko",
        title: "원격 탐사 보정 및 맥락 분석",
        body: "코페르니쿠스, JAXA 및 오픈 Landsat 파생 데이터가 에어로졸 수송, 식생 피복, 토지 환경 등을 포함한 도시 외곽의 분석 범위를 넓힙니다.",
      },
      {
        id: "remote-listening-ko",
        title: "소셜 리스닝 및 도시 내 증언",
        body: "주민들의 불편 제기, 방문객 체감도 및 논의 강도가 분석 지도 데이터가 실제 생활에서 체감되는지 확인해줍니다.",
      },
      {
        id: "remote-judgement-ko",
        title: "최종 도시 평가 종합",
        body: "SLIC 분석가들은 위성 데이터가 인간적 판단을 완전히 대체하는 대신 그것을 보강하고 지원하도록 세 가지 레이어를 함께 판독합니다.",
      },
    ],
    citations: [17, 18, 19, 20, 21, 22, 23, 24, 25],
  },
  equationSection: {
    eyebrow: "수학적 핵심",
    title: "공식 방정식 스택",
    summary: "공개 점수는 고정 가중치, 명시된 방향성 및 공식의 투명성을 사용합니다. 화면에 표시되는 모든 방정식은 장식용이 아닌 실제 방법론의 일부입니다.",
    groups: [
      {
        id: "official-ko",
        eyebrow: "공개 점수",
        title: "공식 발표 수식",
        summary: "사이트에 표시되고 워크북에 적용되는 정확한 공개 점수 로직입니다.",
        equations: [
          {
            id: "official-score-ko",
            title: "공식 SLIC 점수",
            formula: "SLIC(c) = max(0, AMPI_5pillar(c) - penalty(c))",
            explanation: "발표된 점수는 단순 가중 평균이 아닌, 다섯 가지 지조에 대한 가중 AMPI입니다. 편차 항목은 지조 간 불균형에 큰 페널티를 부여합니다. 하나의 지조라도 무너진 도시는 다른 지조들이 우수하더라도 총점이 크게 낮아집니다.",
            citations: [1],
          },
          {
            id: "official-ampi-ko",
            title: "확장된 AMPI 형태",
            formula: officialAmpiFormula,
            explanation: "공개 채점 엔진은 먼저 가중 지조 평균을 계산한 다음, 평균으로 나눈 가중 지조 간 분산 페널티를 뺍니다. 이 수학적 단계는 단편적인 도시 프로필이 높은 점수를 받는 것을 방지합니다.",
            citations: [1],
          },
          {
            id: "disposable-income-ko",
            title: "세금 조정 후 PPP 가용 소득",
            formula: "DI_ppp(c) = ((GrossIncome(c) x (1 - TaxRate(country(c)))) - Rent(c) - Utilities(c) - Transit(c) - Internet(c) - Food(c)) / PPPPrivateConsumptionFactor(country(c))",
            explanation: "이것이 실질적인 여유 생활 공간을 측정하는 핵심 항목입니다. 필수 비용 제외 후의 사후 세금 소득을 PPP 소비 인자를 통해 비교 가능한 구매력 공간으로 단 한 차례 명시적으로 환산합니다.",
            citations: [2, 7],
          },
        ],
      },
      {
        id: "normalization-ko",
        eyebrow: "메트릭 메커니즘",
        title: "표준화 및 커버리지 로직",
        summary: "원시 도시 지표들은 지표의 방향성과 데이터 결측치 처리가 명시적으로 완료된 후에만 병합될 수 있습니다.",
        equations: [
          {
            id: "metric-normalization-ko",
            title: "윈저화된 메트릭 점수",
            formula: "If dir(m) = positive:\n  s_m(c) = 100 x clamp((winsor(x_m(c)) - P5_m) / (P95_m - P5_m), 0, 1)\nIf dir(m) = negative:\n  s_m(c) = 100 x clamp((P95_m - winsor(x_m(c))) / (P95_m - P5_m), 0, 1)",
            explanation: "실제 공표 모델은 고정 백분위수 윈저화(P5/P95)를 거친 후 0-100으로 스케일을 변환합니다. 유해 지표는 분자를 역전시켜 항상 높은 표준화 점수가 양호한 도시 결과를 나타내도록 설계됩니다.",
            citations: [1],
          },
          {
            id: "coverage-score-ko",
            title: "가중 커버리지",
            formula: "Cov_p(c) = Sum over metrics m of alpha_(p,m) x cov_m(c) / Sum over metrics m of alpha_(p,m)\nCov(c) = (25 Cov_pressure + 22 Cov_viability + 18 Cov_capability + 15 Cov_community + 20 Cov_creative) / 100",
            explanation: "데이터 커버리지는 단순 필드 개수가 아닌, 공표된 개별 메트릭의 가중 중요도에 의해 결정됩니다. 직접 메트릭은 1 또는 0으로 기여하며, 복합 메트릭은 해당 하위 항목들의 가중치에 비례하여 기여합니다.",
            citations: [1, 14, 15],
          },
        ],
      },
      {
        id: "subscores-ko",
        eyebrow: "공개 하위 공식",
        title: "독자에게 상시 표시되는 하위 공식",
        summary: "아래 표시된 세부 공식들은 공개 채점판에서 사용되는 워크북 구조와 정확히 일치합니다.",
        equations: [
          {
            id: "growth-pillar-ko",
            title: "Growth 지조",
            formula: growthPillarFormula,
            explanation: "공개 집계식은 실제 삶의 압박을 나타내는 항목들을 직접 측정합니다. 경제성장 모멘텀은 스코어카드 상에 계속 노출되지만, 이는 진단용이며 최종 종합 점수의 계산 공식에는 포함되지 않습니다.",
            citations: [1, 2, 3, 7],
          },
          {
            id: "community-tolerance-ko",
            title: "Tolerance composite",
            formula: toleranceCompositeFormula,
            explanation: "귀속감 및 공동체 지조는 단일 대리 지표가 아닌 검증된 개방성 종합 지표를 활용합니다. 지상 정보가 희박할 경우, 세 번째 항목은 현존하는 국가급 시민권 권리 지표로 대체되어 인위적인 도시 정보 조작을 방지합니다.",
            citations: [1, 14, 16, 35],
          },
          {
            id: "business-growth-ko",
            title: "Economic vitality composite",
            formula: economicVitalityFormula,
            explanation: "거시적 맥락은 중요하지만, 도시 수준의 실제 데이터를 방해하지 않도록 정해진 범위 내로 제한됩니다. 출산율과 기후는 사용자 진단 지표로 표시될 뿐 최종 점수에 직접 투입되지 않습니다.",
            citations: [2, 10, 16],
          },
        ],
      },
    ],
  },
  glossarySection: {
    eyebrow: "표기법 용어 사전",
    title: "각 기호의 의미",
    summary: "표기법은 의도적으로 압축되었습니다. 각 기호는 외부 독자가 점수를 복제하거나 워크시트를 감사할 수 있도록 한 번만 정의됩니다.",
    symbols: [
      { symbol: "c", definition: "도시 또는 기능적 도시 지역", explanation: "점수가 계산되는 도시 단위입니다." },
      { symbol: "m", definition: "메트릭 인덱스", explanation: "하나의 공개 지조 내부에 포함된 점수화된 메트릭 항목입니다." },
      { symbol: "k", definition: "입력 채널", explanation: "직접적으로 또는 복합 메트릭 내부에서 활용되는 원시 입력값입니다." },
      { symbol: "p", definition: "지조 인덱스", explanation: "다섯 가지 공개 지조 중 하나입니다." },
      { symbol: "x_k(c)", definition: "원시 입력값", explanation: "윈저화 전, 도시 c의 입력 채널 k에서 관찰된 원시 값입니다." },
      { symbol: "winsor(.)", definition: "윈저화 연산자", explanation: "채점하기 전에 하위 5% 및 상위 95% 밴드로 극단값을 고정합니다." },
      { symbol: "P5_k, P95_k", definition: "고정 백분위수 경계", explanation: "입력 k에 대한 하위 및 상위 표준화 한계값입니다." },
      { symbol: "s_k(c)", definition: "표준화 점수", explanation: "윈저화 및 방향 조정 후 계산된 0-100 사이의 점수입니다." },
      { symbol: "M_m(c)", definition: "복합 메트릭 점수", explanation: "복합 메트릭 m의 표준화된 구성 요소 점수들의 가중 평균입니다." },
      { symbol: "alpha_(p,m)", definition: "지조 내부의 메트릭 가중치", explanation: "지조 p 내부에서 메트릭 m의 반영 강도를 뜻합니다." },
      { symbol: "cov_m(c)", definition: "메트릭 커버리지", explanation: "관찰된 메트릭의 요구 정보 비중으로, 0에서 1 사이입니다." },
      { symbol: "Cov_p(c)", definition: "지조 커버리지", explanation: "메트릭 가중치를 반영한 지조 p의 데이터 확보 비율입니다." },
      { symbol: "Cov(c)", definition: "전체 가중 커버리지", explanation: "다섯 가지 지조 커버리지 점수들의 가중 평균입니다." },
      { symbol: "w_p", definition: "공개 지조 가중치", explanation: "전체 AMPI 종합 단계에서 지조 p에 적용되는 고정 공개 가중치입니다." },
      { symbol: "mu(c)", definition: "가중 지조 평균", explanation: "AMPI 변동 페널티를 제하기 전 계산된 다섯 가지 지조 점수들의 가중 평균입니다." },
      { symbol: "var(c)", definition: "가중 지조 분산", explanation: "지조 간 불균형에 페널티를 부과하기 위한 가중 분산 값입니다." },
      { symbol: "AMPI(c)", definition: "조정 마조타-파레토 지수", explanation: "커버리지 페널티 적용 전 불균형 조정을 거친 종합 점수입니다." },
      { symbol: "penalty(c)", definition: "커버리지 페널티", explanation: "공표된 커버리지 등급에 따라 부과되는 0점, 5점 또는 15점의 페널티입니다." },
      { symbol: "DI_ppp(c)", definition: "PPP 조정 가용 소득", explanation: "세후 소득에서 필수 비용을 제한 후 PPP 구매력 인자로 1차 환산한 삶의 공간 지표입니다." },
    ],
  },
  workedExampleSection: {
    eyebrow: "계산 사례 상세",
    title: "발표된 데이터 행을 따라가는 산출 연습",
    summary: "이 사례는 장식용 수식이 아닌, 실제 공표된 도시 데이터를 바탕으로 연산 흐름을 보여줍니다.",
    example: {
      city: `${workedExampleDisplayName} 실제 데이터 행`,
      note: "아래 수치들은 `publishedRankingData.json` 실시간 데이터 스냅샷을 따르며, 공개 스코어카드 상의 수치대로 반올림 처리되었습니다.",
      inputs: [
        { label: "DI_ppp raw", value: workedExampleDiRaw, note: `${workedExampleDisplayName}의 공표된 세후 가용 소득 원시 값` },
        { label: "Personal safety raw", value: workedExample?.safety?.raw != null ? String(workedExample.safety.raw) : "—", note: "음의 방향성 지표 표준화 예시에 활용된 Homicide / Harm 원시 입력값" },
        { label: "Pressure pillar", value: formatOneDecimal(workedExample?.pillarScores?.pressure ?? undefined), note: "관측된 가용 지표들에 대한 가중 평균 지조 점수" },
        { label: "Viability pillar", value: formatOneDecimal(workedExample?.pillarScores?.viability ?? undefined), note: "공표된 지조 점수" },
        { label: "Capability pillar", value: formatOneDecimal(workedExample?.pillarScores?.capability ?? undefined), note: "공표된 지조 점수" },
        { label: "Community pillar", value: formatOneDecimal(workedExample?.pillarScores?.community ?? undefined), note: "공표된 지조 점수" },
        { label: "Creative pillar", value: formatOneDecimal(workedExample?.pillarScores?.creative ?? undefined), note: "공표된 지조 점수" },
      ],
      steps: [
        {
          title: "음의 방향성 지표 표준화 예시",
          formula: workedExampleSafetyFormula,
          result: `SafetyScore = ${formatOneDecimal(workedExample?.safety?.scoreRounded ?? undefined)}`,
          explanation: `${workedExampleDisplayName}의 개인 안전(Personal Safety) 입력값은 역방향 지표이므로 분자가 반전됩니다. 여기에 사용된 P5/P95 경계치는 실제 채점기에 적용된 고정 \`normStats\`에서 가져옵니다.`,
        },
        {
          title: "Growth 지조 가중 평균",
          formula: workedExamplePressureFormula,
          result: `Growth = ${formatOneDecimal(workedExample?.pressure?.scoreRounded ?? undefined)}`,
          explanation: "관측된 유효 지표만이 분모 계산에 사용됩니다. 경제성장 모멘텀은 스코어카드 상에 존재하나 실제 점수 계산에는 투입되지 않습니다.",
        },
        {
          title: "부문 간 가중 평균 및 분산",
          formula: workedExampleMeanFormula,
          result: `mu = ${formatThreeDecimals(workedExample?.overall?.weightedMeanExact ?? undefined)}, var = ${formatTwoDecimals(workedExample?.overall?.weightedVarianceExact ?? undefined)}`,
          explanation: `이것이 실질적인 지조 간 불균형 페널티 부과 단계입니다. 만약 ${workedExampleDisplayName}가 같은 평균값을 가지면서 더 균일한 지조 점수를 냈다면 총점은 더 높았을 것입니다.`,
        },
        {
          title: "AMPI 및 최종 공표 점수",
          formula: workedExampleAmpiFormula,
          result: `SLIC = ${formatOneDecimal(workedExample?.overall?.slicScoreRounded ?? undefined)}`,
          explanation: `AMPI의 불균형 페널티로 인해 최종 점수는 지조 평균(mu)보다 낮아집니다. 또한 ${workedExampleDisplayName}의 데이터 커버리지는 ${workedExample?.overall?.coverageGrade ?? "—"} 등급이므로 커버리지 미달에 따른 추가 감점은 없습니다.`,
        },
      ],
      finalScore: formatOneDecimal(workedExample?.overall?.slicScoreRounded ?? undefined),
      conclusion: "이 연산 예시가 시사하는 바는 방법론적 정직함입니다: Viability나 Capability가 아무리 우수해도 공동체(Community) 지조의 약점을 자동으로 가릴 수는 없습니다. 편차 페널티 덕분에 SLIC는 단편적인 부분적 우수성을 종합적인 살기 좋음으로 혼동하지 않습니다.",
    },
  },
  modelSection: {
    eyebrow: "방법론적 경계",
    title: "독립된 진단용 지표와 단일 공개 점수 공식",
    summary: "공개 점수는 하나의 선언된 AMPI 모델을 통해 결정됩니다. 진단용 지표들은 화면에 노출되나 총점에 어떠한 암묵적 영향도 주지 않습니다.",
    families: [
      {
        id: "weighted-ko",
        title: "공식 발표 모델",
        formula: officialSlicFormula,
        role: "공표 점수",
        explanation: "유일하게 반영되는 공표용 산출 수식입니다: 고정 가중치, 윈저화된 정규화, 가중 지조 평균, 지조 간 가중 AMPI 산출, 그리고 투명한 커버리지 감점 체계.",
      },
      {
        id: "diagnostics-ko",
        title: "내부 진단 지표",
        formula: "Diagnostics(c) do not modify SLIC(c)",
        role: "비채점 분석 항목",
        explanation: "경제 성장 모멘텀, 기후/일조량 여건, 출생률 관련 전망 지표 등은 스코어카드 상에 계속 표시될 수 있으나 실제 종합 점수에는 가중치가 반영되지 않습니다.",
      },
      {
        id: "profile-match-ko",
        title: "탐색형 프로필 매칭",
        formula: "Match(c,u) = similarity(profile(c), preference(u))",
        role: "자가 진단용",
        explanation: "방사형 거미줄 그래프 활동은 공식 순위를 변경하지 않습니다. 이는 도시가 가진 지조별 점수 형태와 사용자가 설정한 개인 선호도를 비교하여 유사성을 분석하는 데 그칩니다.",
      },
    ],
  },
  countryContextSection: {
    eyebrow: "국가 맥락 정보",
    title: "거시 경제력은 고려하되, 전체 순위를 지배하지는 못하게 차단",
    summary: "1인당 GDP, 성장률, 불평등 지수, PPP 및 세율은 모두 중요하지만, SLIC 점수에서는 결정적 척도가 아닌 제한된 통제 및 조정 지표로서만 기능합니다.",
  },
  weightChartLabel: "공식 점수 대비",
  pillarsSection: {
    eyebrow: "공식 지조(Pillars)",
    title: "종합 점수를 산출하는 다섯 가지 지조",
    summary: "아래의 각 부문은 공표된 채점판에서 적용되는 가중치 및 세부 구성 요소 구조와 완벽히 일치합니다.",
  },
  pillars: [
    {
      id: "pressure",
      name: "Growth",
      weight: 25,
      thesis: "경제 활력은 도시의 궤적을 결정하지만, 이에 수반되는 주거비, 과도한 노동 시간, 부채 및 심각한 심리적 스트레스 등의 생활 압박은 가용 생활 공간을 정직하게 반영해야 합니다.",
      justification: "이 지조는 명성에 숨겨진 삶의 실질적인 압박 요인들을 정밀하게 평가하여 가용 공간을 채점의 중심에 둡니다. 경제성장률 등은 보조 지표로만 기능합니다.",
      citations: [2, 3, 7],
      metrics: [
        { name: "세금 조정 후 PPP 가용 소득", weight: 9, description: "필수 비용을 공제하고 세후에 남는 가용 가계 자금이며, 1회에 한해 PPP 소비 인자로 환산되어 실제 구매력 척도로 사용됩니다.", inputs: ["총소득", "세율", "주택 임차료", "공공요금", "인터넷 비용", "대중교통 비용", "식비", "PPP 인자"] },
        { name: "주택 가격 압박", weight: 5, description: "평당 실제 매매 시세입니다. 주거 비용이 급등할수록 세대당 자산 형성의 기회가 박탈되므로 음의 반영 비율을 갖습니다.", inputs: ["평방미터당 USD", "도시 시장 매매 가격"] },
        { name: "가계 부채 부담", weight: 4, description: "가계의 가처분소득 대비 부채 총량 또는 최적 대리값의 비율입니다.", inputs: ["가계 부채 대리 지표"] },
        { name: "근로 시간 압박", weight: 4, description: "주당 평균 근로 시간 및 장기 과로 비중입니다. 주 40시간 초과 근로가 만연할수록 도시 점수는 감점됩니다.", inputs: ["주당 근로시간", "초과 근로 비율"] },
        { name: "자살 및 정신적 압박", weight: 3, description: "도시의 극단적인 정신적 피로도를 나타내는 대리 보건 지표입니다.", inputs: ["연령 표준화 자사항 지표"] },
        { name: "경제적 스트레스 (Hanke 고통 지수)", weight: 2, description: "Hanke 연간 고통지수 2025: (2×실업률) + 인플레이션율 + 대출 금리 - 실질 GDP 성장률입니다. 국가 수준 지표.", inputs: ["실업률", "CPI 인플레이션", "은행 대출 금리", "실질 1인당 GDP 성장률"] },
      ],
    },
    {
      id: "viability",
      name: "Viability",
      weight: 22,
      thesis: "도시의 일상은 안전하고, 쾌적하게 호흡하며 이동할 수 있으며, 공공서비스가 효율적이되 강압적이지 않아야 합니다.",
      justification: "이 지조는 스마트 시티 전시 행정이 아닌 체감되는 결과물을 채점합니다. 기후 여건은 진단 보조선으로 노출되나, 지조 합산은 아래 실측된 지표들로 제한됩니다.",
      citations: [3, 5, 11, 13, 17],
      metrics: [
        { name: "개인 안전", weight: 5, description: "강력 범죄 발생율, 외지인 대상 범죄율 및 야간 보행 안심 정도를 통합 측정합니다.", inputs: ["살인 사건", "강력 폭력 범죄", "범죄 피해 조사", "야간 안전 대리 지표"] },
        { name: "대중교통 접근성 및 통근 시간", weight: 5, description: "광역 교통망 확보 수준 및 평균 출퇴근 소요 시간입니다. (현재 데이터 부족으로 일시 유예 상태이며, 0점 처리됩니다)", inputs: ["GTFS 대중교통 데이터", "통근 시간", "커버리지"] },
        { name: "깨끗한 공기", weight: 4, description: "미세먼지(PM2.5) 연평균 수치 및 환경 기준치 초과 일수를 CAMS 및 OpenAQ 정보를 보완하여 반영합니다.", inputs: ["PM2.5 농도", "기준 초과 일수", "에어로졸 맥락"] },
        { name: "상하수도 및 공공설비 안정성", weight: 4, description: "안정적인 수도 공급과 안전한 하수 처리율 및 정전/단수 빈도를 의미합니다.", inputs: ["WASH 물·위생 접근성", "단수·단전 서비스 중단", "수질·서비스 안전 규정 준수"] },
        { name: "디지털 인프라", weight: 4, description: "광대역 고속통신망 품질, 요금 감당력 및 광랜 구축 정도를 포함합니다.", inputs: ["고정 광대역 초고속인터넷", "요금 감당 가용성", "인터넷 품질 성능"] },
        { name: "기후 및 일조 만족도", weight: 7, description: "연간 일조 시간, 기온 쾌적도 및 극단적 자연 재해에 노출되는 빈도를 가중 합산한 복합 지표입니다.", inputs: ["일조 시간", "기온 쾌적도", "자연 재해 강도"] },
      ],
    },
    {
      id: "capability",
      name: "Capability",
      weight: 18,
      thesis: "신뢰할 수 있는 도시는 청소년과 시민들에게 안전한 의료, 고품질 교육, 그리고 공평한 사회 진출을 보장합니다.",
      justification: "단순 병원 수나 학교 개수가 아닌, 실질적 기회의 질과 접근성 보장을 중시합니다.",
      citations: [3, 6, 8, 9, 14, 15],
      metrics: [
        { name: "보건 의료 질", weight: 8, description: "회피 가능 사망률 및 의료 설비 능력과 공공 의료 혜택의 실효성을 뜻합니다.", inputs: ["회피 가능 사망률", "의료 서비스 평판", "의료 인프라 수용력"] },
        { name: "교육 서비스의 질", weight: 6, description: "PISA 학습 도달도 및 수료율, 미래 산업 적합 직업 훈련 수준입니다.", inputs: ["PISA 학업 성취도", "UIS 교육 지표", "학업 수료율", "기술 인재 육성력"] },
        { name: "기회 균등 및 분배 정의", weight: 4, description: "성별 격차 지수, 구직 단념 청년(NEET) 비율 및 세후 지니계수 격차를 통합한 지표입니다.", inputs: ["성별 격차 정보", "청년 니트(NEET) 비율", "지니 계수", "고용 격차"] },
      ],
    },
    {
      id: "community",
      name: "Community",
      weight: 15,
      thesis: "도시는 단순한 일터나 주거지가 아닙니다. 환대와 관용, 문화적 열린 태도, 그리고 귀속감이 있어야 사람들이 떠나지 않습니다.",
      justification: "SLIC는 단순 브랜드 홍보가 아닌, 실제 관용도를 수치화하여 포용력 있는 도시에 합당한 가치를 배정합니다. 출생률은 보조 참고 지표입니다.",
      citations: [1, 14, 16],
      metrics: [
        { name: "문화 및 공공 활력", weight: 7, description: "도심 속 제3의 여가 공간, 역사적 자산 보존, 축제 및 주민 체감을 검증한 관광 유입 규모입니다.", inputs: ["여가 시설 수", "행사 개최 수", "공공 관심도", "관광 유입 규모"] },
        { name: "환대와 귀속감", weight: 6, description: "순유입 인구 추이, 거주자 애착도 및 외국어 사용 편의성 등을 통합한 값입니다.", inputs: ["순이주 유입", "평판 감사 및 실증 조사", "다국어 지원 인프라"] },
        { name: "개방성과 다양성", weight: 4, description: "LGBTQ+ 보호 법안 범위, 사회적 차별 지표 및 마찰 없는 취업의 다양성 기회입니다.", inputs: ["성소수자 법적 권리", "차별 대리 지표", "시장 진입 개방성"] },
        { name: "사회적 낙관 (출생률 기준)", weight: 2, description: "세계은행의 총출산율(TFR) 자료를 사회 전반의 미래 신뢰 척도로 가볍게 반영하며, 주도적 점수 결정력은 갖지 않습니다.", inputs: ["세계은행 총출산율(TFR)"] },
        { name: "시민적 자유와 존엄", weight: 4, description: "HRMI 권한 부여 점수(0.4), Freedom House 자유 지수(0.3), V-Dem 자유 민주주의 지수(0.3)를 결합한 복합 지표입니다.", inputs: ["HRMI 권한 부여 점수", "Freedom House FIW", "V-Dem LDI"] },
      ],
    },
    {
      id: "creative",
      name: "Creative",
      weight: 20,
      thesis: "도시는 고통을 줄이는 데 그치지 않고, 주민들의 새로운 도전, 발명 및 비즈니스 활력과 경제 혁신을 장려해야 합니다.",
      justification: "이 지조는 안락함이 정체로 이어지지 않게 하고 지식 정보 경제의 창출 능력을 정밀하게 측정합니다. 관광/유흥 등 오락 목적은 공동체 지조에 분류됩니다.",
      citations: [2, 10, 16],
      metrics: [
        { name: "기업가 정신 생동력", weight: 6, description: "신규 비즈니스 창업률, 스타트업 집적화 속도 및 기업 도약 속도입니다.", inputs: ["신규 기업 밀도", "신생 법인 창출", "스타트업 창업 활동"] },
        { name: "혁신 및 연구 역량", weight: 5, description: "특허 출원 수, 민간/공공 R&D 지출 규모 및 연구 시설 인프라 역량입니다.", inputs: ["특허 출원", "R&D 지출", "연구 학술 기관"] },
        { name: "경제 활력 및 생산적 맥락", weight: 5, description: "벤처 투자 금액, 생산성 향상 비율 및 도시 거시 성장 안전 궤도입니다.", inputs: ["투자 유치 신호", "1인당 GDP(PPP)", "GDP 성장률"] },
        { name: "행정 및 규제 마찰", weight: 4, description: "인허가 발급 소요 일수, 행정 편의성 및 규제 일관성에 따른 투자 방해 강도입니다.", inputs: ["행정 처리 지연", "인허가 발급 부담", "규제 정책 일관성"] },
      ],
    },
  ],
  protocolSection: {
    eyebrow: "순위 책정 프로토콜",
    title: "도시의 진입, 편입 유지 및 최종 공표 절차",
    summary: "순위 책정은 정보 누락 및 규모적 변인을 정직하게 다루어야 합니다. 유명 도시라고 해서 자동 진입권을 주지 않으며, 데이터가 부실한 도시는 허위의 소수점 계산으로 왜곡되지 않게 처리됩니다.",
  },
  rules: [
    {
      title: "행정구역 경계가 아닌, 기능적 도시 권역(FUA) 적용",
      body: "SLIC는 단순 임의적 자치 구역의 범위를 넘어 실제 노동 공급 및 공공 서비스 혜택이 미치는 광역 노동 시장을 측정 단위로 설정합니다.",
      citations: [12],
    },
    {
      title: "공인된 가중치 준수",
      body: "공개 스코어보드는 단일 공개 가중치 설정 및 지조 간 변동성 차단용 AMPI 조정을 바탕으로 일관되게 작용합니다. 사용자 정의 가중치 설정은 탐색 목적으로 제한됩니다.",
      citations: [1],
    },
    {
      title: "사전 커버리지 게이트 필수",
      body: "도시는 가중치 반영 후 데이터 확보 수준이 일정 기준을 넘을 때만 순위에 진입합니다. 기준 미달 도시는 순위표에서 제외되며 감시 대상(Watchlist)으로 분류됩니다.",
      citations: [1, 14, 15],
    },
    {
      title: "안전은 기기의 감시가 아닌 실제 결과값 기준",
      body: "단순 카메라 개수나 인프라 쇼케이스는 그 자체만으로 점수를 받지 못합니다. 범죄율 하락과 일상적 안전 체감도가 반영됩니다.",
      citations: [1, 3],
    },
    {
      title: "관용성은 관측된 실질적 영향력 평가",
      body: "SLIC는 종교적, 정체성적 신념 자체를 평가하지 않습니다. 대신 모든 배경의 주민들이 마찰이나 차별 없이 거주하고 취업할 권리를 가질 수 있는지 실생활 수준에서 측정합니다.",
      citations: [1, 14],
    },
    {
      title: "방문 수요는 부차적 참고 지표로 적용",
      body: "관광 유입은 도심 혼잡도, 안전 여건, 생태 용량 등이 생활권에 압박을 주지 않는 범위 내에서만 반영됩니다. 방콕의 유입 비용 지표들은 관광 접근성이 실제 낮은 생활 비용과 결부되어 있음을 나타내나, 이 자체가 직접적인 가산점 요소가 되는 것은 아닙니다.",
      citations: [1, 36, 37],
    },
    {
      title: "V3.3: 순수 점수 순위 책정 후, 별도의 공개 층 등급 부여",
      body: koreanTierProtocolRule,
      citations: [],
    },
    {
      title: "V3.3: 신 규정에 따른 싱가포르와 방콕의 배치 결과",
      body: koreanSingaporeRule,
      citations: [],
    },
    {
      title: "V3.2: 분쟁 지역 감시 대상(Watchlist) 정책",
      body: "실제 미사일/폭격 위협을 받거나 긴급 대피령이 반복되는 등 전쟁 또는 물리적 공격 하에 놓인 도시는 정식 순위 산출에서 유예되며 별도 분쟁 지역 감시 대상에 등록됩니다. 도시 카드는 유지되나 비평화 지역과의 불공정한 살기 좋음 척도 비교를 방지하기 위함입니다. ceacefire 등 평화 정착을 거친 후 순위표 복귀가 결정됩니다.",
      citations: [],
    },
    {
      title: "V3.1: 주택 부담금 한도 확대",
      body: "주거 비용 부담 윈저화 한계가 평당 실제 시세 기준으로 확대되어 고가 주거비 도시들 간 차등적 고통 분담 지표가 더 정확히 반영됩니다. 주거 비용 페널티는 압박(Growth) 지조의 점수를 깎게 설계되었습니다.",
      citations: [],
    },
    {
      title: "단순 진단 지표는 숨겨진 가중치가 아님",
      body: "성장률, 날씨, 출산율 등은 스코어카드 상에는 진단용 지표로 표시되나, 실제 최종 순위 가중 계산 공식에는 아무 가산 혹은 감점 기여도 없습니다.",
      citations: [],
    },
    {
      title: "복합 지표의 구성 비율은 완전 투명하게 유지",
      body: "기회 평등, 관용도, 경제 생동력 등은 투명하게 공개된 가중 하위 비율로만 계산되며, 정보 부재 시 관측된 항목들로 비율이 재조정될 뿐 은밀한 편향이 대입되지 않습니다.",
      citations: [],
    },
    {
      title: "V3: PPP 환산은 단 1차례 단일 적용",
      body: "SLIC는 세후 가용 소득을 비교할 때 PPP 소비 인자 단 하나만을 활용하여 가용 소득 메트릭 내부에서 1차 계산합니다. 이는 다른 복잡한 2차 조정으로 인한 불명확한 수치 누락을 사전에 제거해 줍니다.",
      citations: [],
    },
  ],
  sourceSection: {
    eyebrow: "소스 등급 체계",
    title: "모델이 최우선으로 신뢰하는 정보",
    summary: "아래 데이터 사다리는 정보 확보 거리의 투명성을 드러냅니다. 도시 수준의 실측 정보가 국가 대체 지표보다 앞서며, 감사 검증을 거친 지표가 불명확한 편의 지표보다 앞섭니다.",
  },
  sourceTiers: koreanSourceTiers,
  worksheetSection: {
    eyebrow: "채점 워크시트",
    title: "순위 책정 이면의 도시별 워크시트 정보",
    summary: "도시 목록이 확정되면, 아래의 속성 칼럼이 채워지고 모델은 각 지조 점수와 최종 SLIC 점수 및 커버리지 등급을 순차 계산해 냅니다.",
  },
  worksheetColumns,
  referencesSection: {
    eyebrow: "참고 자료",
    title: "이 프레임워크를 뒷받침하는 연구 출처 목록",
    summary: "방법론 페이지는 본 프로젝트를 지탱하는 내부 벤치마킹 메모 및 실제 공개 공식과 워크북에 고정된 공식 문서들을 활용했습니다.",
  },
  references: methodologyReferences,
};
