import { PUBLIC_TIER_RULES } from "./publicTierPolicy.js";
import type { MethodologyData, SourceTier } from "./types";
import {
  singaporeCity,
  bangkokCity,
  workedExample,
  workedExampleDisplayName,
  workedExampleDiRaw,
  workedExampleSafetyFormula,
  workedExamplePressureFormula,
  workedExampleMeanFormula,
  workedExampleAmpiFormula,
  formatOneDecimal,
  formatTwoDecimals,
  formatThreeDecimals,
  officialSlicFormula,
  officialAmpiFormula,
  growthPillarFormula,
  toleranceCompositeFormula,
  economicVitalityFormula,
  methodologyReferences,
  worksheetColumns,
  alphaCountryExclusionList,
  alphaCityExclusionList,
  maxJapanCrossTier,
} from "./methodologyShared";

export const japaneseTierProtocolRule =
  `公開順位はまず正確な非四捨五入 SLIC スコア順で決定され、Alpha・Beta・Gamma は順位の後に別途適用される公開オーバーレイです。順位番号の内側に地理的フィルターは隠されていません。 ` +
  `公開層オーバーレイは三層合計で原則として1国1都市ですが、現行プロトコルでは台湾が${PUBLIC_TIER_RULES.maxTaiwanAcrossPublicTiers}スロット、日本が${maxJapanCrossTier}スロットを保有できます。Alpha は Community >= ${PUBLIC_TIER_RULES.alphaMinCommunity}、Pressure >= ${PUBLIC_TIER_RULES.alphaMinPressure}、カバレッジグレード ${PUBLIC_TIER_RULES.alphaMinCoverageGrade} 以上を要件とし、欠損したプレッシャーデータを最高層の主張に変換することはできません。ヨーロッパは Alpha で最大 ${PUBLIC_TIER_RULES.maxEuropeInAlpha}席、オセアニア ${PUBLIC_TIER_RULES.maxOceaniaInAlpha}席、韓国 ${PUBLIC_TIER_RULES.maxSouthKoreaInAlpha}席、日本 ${PUBLIC_TIER_RULES.maxJapanInAlpha}席に制限されます。${alphaCountryExclusionList} は国別ルールにより Alpha から除外され、${alphaCityExclusionList} は編集部の生活費ルールにより Alpha から除外されます。 ` +
  `Beta は同じ国別ルールと台湾・日本の例外を維持しながら、Community >= ${PUBLIC_TIER_RULES.betaMinCommunity}、Pressure >= ${PUBLIC_TIER_RULES.betaMinPressure} へと居住適合性の下限を引き上げます。Gamma は残りのランク都市から補充されます。`;

export const japaneseSingaporeRule =
  singaporeCity && bangkokCity
    ? `シンガポールの現在の純スコア順位は第 ${singaporeCity.rank} 位、SLIC は ${formatOneDecimal(singaporeCity.slicScore)}、Coverage は ${singaporeCity.coverageGrade} ですが、公開層オーバーレイはシンガポールを ${singaporeCity.tierLabel ?? "公開層外"}に配置しています。 ` +
      `Viability（${formatOneDecimal(singaporeCity.viabilityScore)}）と Capability（${formatOneDecimal(singaporeCity.capabilityScore)}）は依然として高水準ですが、Community（${formatOneDecimal(singaporeCity.communityScore)}）は Alpha の下限 ${PUBLIC_TIER_RULES.alphaMinCommunity} と Beta の下限 ${PUBLIC_TIER_RULES.betaMinCommunity} の両方を下回り、Pressure（${formatOneDecimal(singaporeCity.pressureScore)}）は Alpha 基準はクリアするが Beta 基準はクリアしません。 ` +
      `バンコクは逆の結果を示しています。純スコア順位第 ${bangkokCity.rank} 位、SLIC ${formatOneDecimal(bangkokCity.slicScore)} でありながら ${bangkokCity.tierLabel ?? "公開層"}に入りますが、これは Community（${formatOneDecimal(bangkokCity.communityScore)}）と Pressure（${formatOneDecimal(bangkokCity.pressureScore)}）の両方が Alpha 基準を超え、より上位にランクされたタイの都市がタイの公開層スロットを先に占有していないためです。独立した旅行コストの情報源はバンコクの公開価値提案を裏付けていますが、これは文脈的証拠であり、観光コストパフォーマンスのスコアリングボーナスではありません。`
    : "このページがシンガポールとバンコクを引用するのは、両都市の現在の行がライブデータセットに存在する場合に限られます。";

export const japaneseSourceTiers: SourceTier[] = [
  {
    tier: "第1層",
    title: "都市・大都市圏公式データ",
    description: "オープンデータポータル、公益事業規制機関、交通データフィード、病院公開資料、都市統計局。",
  },
  {
    tier: "第2層",
    title: "州・県・準国家公式データ",
    description: "地域統計機関、大都市圏観測所、準国家行政データセット。",
  },
  {
    tier: "第3層",
    title: "国家・国際公式データセット",
    description: "World Bank、WHO、ILO、UNESCO UIS、OECD、WIPO および WHO/UNICEF JMP。",
  },
  {
    tier: "第4層",
    title: "検証済み二次・実験的レイヤーデータ",
    description: "OpenAQ、Copernicus CAMS、Sentinel-2 / Sentinel-5P 文脈レイヤー、JAXA 土地被覆データ、Landsat 派生植生レイヤー、M-Lab、ソーシャルリスニング、クラウドソーシング生活費レイヤー、および明示的な注意書き付きの都市証言。",
  },
  {
    tier: "第5層",
    title: "アナリスト評価・クロス検証",
    description: "実地経験、クロス検証調査、専門知識に基づく SLIC アナリストの手動評価。寛容性、ホスピタリティ、文化的生活など、純粋なデータ収集が困難な定性的シグナルに使用されます。",
  },
];

export const methodologyDataJa: MethodologyData = {
  hero: {
    eyebrow: "方法論ペーパー",
    title: "SLIC 方法論",
    strapline: "V3: 数値がどのように構築されているかを示す診断モデル。",
    intro: "V1は釜山を1位としたスプレッドシートでした。V2は台北のステージで発表され、都市の指導者たちから「私の都市でもこれができるか」という質問を受けました。V3では測定ロジックをより厳格にしました。現在、すべての数値は宣言された入力に直接结びついており、スコア化された項目は目に見える診断指標と分離され、部門間の不均衡はAMPIを通じて明示的にペナルティが課されます。また、ワークベンチにより、読者は公表されたランクと混同することなく、さまざまなウェイトプロファイルをテストできます。モデルはオープンです。公式は宣言されています。すべての都市の数値を監査できます。",
    doctrineTitle: "V3 ドクトリン",
    doctrineBody: "SLICは都市をブランドや貸借対照表としてだけでなく、生きたシステムとして扱います。モデルは、可処分性、安全性、文化的・公的生活、寛容性、成長条件、阻害要因、そして人々が実際に生活するための現実的な空間を追跡します。",
    contextTitle: "国別コンテキスト入力値",
    contextItems: [
      "1人当たりGDP (PPP)",
      "GDP成長率",
      "ジニ係数",
      "ユーザー指定の税率",
      "PPP民間消费因子",
    ],
    explicitTitle: "公開公式が明示するもの",
    explicitItems: [
      "安全性は監視の強さではなく、結果によってスコア化されます。",
      "寛容性は低摩擦な共存と平等な市場参入を通じてスコア化されます。",
      "ビジネスの活力は明示的にスコア化され、マクロ経済の文脈は目に見える形で制限され、暗黙的に支配することはありません。",
    ],
  },
  readerGuide: {
    eyebrow: "リーダーガイド",
    title: "一般読者にはわかりやすく、分析者には再現可能に",
    summary: "方法論は、平易な言葉で議論を理解したい人々と、独自の都市ユニバースでスコアを実行したい人々の両方に同時に応える必要があります。",
    layTitle: "平易な言葉による読解パス",
    technicalTitle: "技術的再現パス",
    laySteps: [
      "5つの柱を5つの公開された質問として捉えてください：負担可能性、日々の生存性、能力、帰属意識、そして創造的・経済的モメンタム。",
      "テクノロジーは実現のための支援レイヤーとして扱ってください。測定可能な日々の状況が改善されて初めて意味を持ちます。",
      "高コスト都市は、生活圧力の項目と並べて読んでください。制度的な強さは、住宅や時間の圧迫を打ち消すものではありません。",
      "地方・中堅都市も同じ基準値で評価してください。知名度が低いからといって、測定フレームから除外されるわけではありません。",
    ],
    technicalSteps: [
      "都市を機能的都市地域（FUA）または合理的に定義可能な都市圏単位として定義します。",
      "都市データを最優先で収集し、次に準国家、最後に国家代替データを適用し、各指標のソースティアを記録します。",
      "スコアリングの前に、税調整済みのPPP可処分生活空間を計算します。給与単体では不十分です。",
      "下位5%および上位95%でウィンザー化（外れ値処理）を行い、0〜100に正規化し、有害な指標を反転スコア化し、スコア化された指標と診断指標を分離し、カバレッジグレードをランキングと同時に公開します。",
    ],
  },
  critiqueSection: {
    eyebrow: "既存のランキングが失敗する理由",
    title: "SLICが埋めようとしている溝",
    summary: "既存の都市指数は研究対象として有用ですが、その多くはSLICが宣言した測定フレームとは異なる都市理論を前提としています。",
  },
  critiques: [
    {
      title: "知名度や名声がしばしば住みやすさと混同されます",
      body: "多くのランキングは、制度的な洗練さ、支出、ブランドの明確さを優遇することで、すでに豊かで高度に形式化された都市を構造的に押し上げています。",
      implication: "SLICは、生きた生存性と都市のプレステージを分離し、1人当たりGDPを運命ではなく文脈として扱います。",
      citations: [1, 2, 14],
    },
    {
      title: "データ不足により、過小評価された都市がスコアリングの前に見落とされます",
      body: "地方・中堅都市は、ベンチマークアーキテクチャが都合のよい既存データセットを持つ都市しか受け入れないため、除外されがちです。",
      implication: "SLICはウォッチリストを保持し、カバレッジグレードを公開し、黙って都市を削除するのではなく、目に見えるソースラダーを使用します。",
      citations: [1, 14, 15],
    },
    {
      title: "安全性がスマート機器の設置数から推測されがちです",
      body: "アプリ、ダッシュボード、監視カメラなどのハードウェアは目に見えますが、実際の住みやすさは安全でなかったり、強圧的であったりすることがあります。",
      implication: "SLICは、被害、暴力犯罪、日々の信頼度を直接スコア化します。カメラ自体がポイントを獲得することはありません。",
      citations: [1, 11, 13],
    },
    {
      title: "生活圧力が過小評価されがちです",
      body: "必需品支出後の可処分所得、負債、労働時間、自殺率は実際の都市生活の核心ですが、二次的なものとして扱われるか、完全に欠落していることが多いです。",
      implication: "SLICは生活圧力と生活空間に、それぞれ独自の完全な公式ウェイトを与えます。",
      citations: [1, 2, 3, 7],
    },
    {
      title: "観光客数は有益ですが、自動的にプラスになるわけではありません",
      body: "観光客の多さは、混雑、犯罪、または搾取的な都市環境と共存することがあります。",
      implication: "SLICは旅行需要を文脈的な文化的需要シグナルとして扱いますが、安全性、環境、市民社会への圧力チェックを通過する必要があります。",
      citations: [1],
    },
  ],
  processSection: {
    eyebrow: "手法の検証",
    title: "会議室、パネル、ワークショップでのモデルのストレステスト",
    summary: "SLICは一回限りのスプレッドシートではありません。フレームワークは、公開公式として確定される前に、ライブセッションで繰り返し説明され、挑戦され、修正されました。",
    figures: [
      {
        id: "process-stage-ja",
        src: "/photos/report-people-stage.jpg",
        alt: "公開された都市イベントのステージ上の人々。",
        caption: "フレームワークは個人的な起草だけでなく、公開されたプレゼンテーションにも耐えなければなりませんでした。",
        width: 1440,
        height: 1440,
      },
      {
        id: "process-meeting-ja",
        src: "/photos/report-people-meeting.jpg",
        alt: "ノートパソコンとマイクを置いたテーブルを囲む会議の参加者。",
        caption: "仮定は、データの選択と都市のロジックを擁護しなければならない作業会議でテストされました。",
        width: 1439,
        height: 1085,
      },
      {
        id: "process-workshop-ja",
        src: "/photos/report-people-workshop.jpg",
        alt: "着席した聴衆にプレゼンテーションを行う講師のワークショップ。",
        caption: "パイロットディスカッションは、「見栄えの良い」指標と、実際の都市生活を説明する指標を区別するのに役立ちました。",
        width: 2048,
        height: 1365,
      },
    ],
  },
  flowSection: {
    eyebrow: "スコアの流れ",
    title: "生指標が公開SLICスコアになるまで",
    summary: "スコアフロー is あえて短く監査可能に設計されています：生指標、正規化された指標スコア、柱の集計、そして最終的な加重スコア。",
    stages: [
      {
        id: "raw-ja",
        title: "生の指標",
        body: "目に見えるソースティアとともに、都市、大都市圏、準国家、国家レベルの信号を収集します。",
        formula: "x_m(c)",
      },
      {
        id: "normalized-ja",
        title: "正規化",
        body: "P5/P95でウィンザー化を行い、0〜100に正規化し、有害な変数は逆スコア化します。",
        formula: "s_m(c)",
      },
      {
        id: "pillars-ja",
        title: "柱の集計",
        body: "宣言された内部ウェイトに基づいて、指標スコアを公開された柱に集計します。",
        formula: "P_p(c) = Sum observed alpha_(p,m) x s_m(c) / Sum observed alpha_(p,m)",
      },
      {
        id: "final-ja",
        title: "最終スコア",
        body: "固定された1つの公開方程式を適用し、カバレッジグレードを添付します。",
        formula: "SLIC(c)",
      },
    ],
  },
  remoteSensingSection: {
    eyebrow: "リモートセンシングレイヤー",
    title: "地上センサーがまばらな場合、衛星の証拠が都市の枠組みを広げる",
    summary: "SLICは、地上観測ステーションが非常に少ない、偏っている、または不均一で、都市全体の大気環境や生態系境界を十分に表現できない場合に、空間カバレッジを広げるためにリモートセンシングを使用します。衛星レイヤーは補助的な証拠であり、魔法の真実ではありません。",
    quantifyTitle: "衛星レイヤーが定量化に役立つもの",
    quantifyItems: [
      "より広い都市大気圏にわたるエアロゾル負荷と大気組成",
      "NDVIスタイルの土地データによる植生と緑量バッファリング",
      "高密度建物の周囲の土地被覆、水分、表面コンテキスト",
      "地上ステーションネットワークが見落とす可能性のある広域の汚染ドリフト",
    ],
    qualifyTitle: "アナリストが依然として適格性を判断する必要があるもの",
    qualifyItems: [
      "地形、海岸線、風の流れ、季節的な煙の経路",
      "局所的なホットスポットと都市全体の状況との違い",
      "都市の形状、ストリートキャニオン、住民が実際に経験する暴露の様子",
      "公式の環境記録、証言、都市の証拠からのグラウンドトゥルース（地上検証データ）",
    ],
    workflowTitle: "衛星レイヤーが手法に組み込まれる流れ",
    workflowStages: [
      {
        id: "remote-official-ja",
        title: "公式の都市および環境記録",
        body: "地上センサー、ユーティリティレポート、大気質記録、および公式環境リリースは、利用可能な場合は引き続き主要なレイヤーです。",
      },
      {
        id: "remote-context-ja",
        title: "リモートセンシングの補正と文脈",
        body: "コペルニクス、JAXA、およびオープンなLandsat派生レイヤーが、エアロゾル輸送、植生被覆、土地のストレス、および都市の生態系エッジのフレームを広げます。",
      },
      {
        id: "remote-listening-ja",
        title: "ソーシャルリスニングと都市の証言",
        body: "住民の苦情、訪問者の証言、議論の強度は、マップされた条件が実際の生活都市でどのように感じられているかを特定するのに役立ちます。",
      },
      {
        id: "remote-judgement-ja",
        title: "最終的な都市の判定",
        body: "SLICのアナリストは3つのレイヤーすべてを一緒に読み取るため、衛星の証拠は判定を完全に代替するのではなく、意思決定をサポートします。",
      },
    ],
    citations: [17, 18, 19, 20, 21, 22, 23, 24, 25],
  },
  equationSection: {
    eyebrow: "数学的コア",
    title: "公式方程式スタック",
    summary: "公開スコアは、固定ウェイト、宣言された方向性、および数式の透明性を使用します。表示されているすべての方程式は、装飾的な数学ではなく、実際の手法の一部です。",
    groups: [
      {
        id: "official-ja",
        eyebrow: "公開スコア",
        title: "公式発表数式",
        summary: "サイトに表示され、ワークブックに反映される正確な公開スコアロジックです。",
        equations: [
          {
            id: "official-score-ja",
            title: "公式SLICスコア",
            formula: "SLIC(c) = max(0, AMPI_5pillar(c) - penalty(c))",
            explanation: "公開されるスコアは、単純な加重平均ではなく、5つの柱にわたる加重AMPIです。分散項により、部門間の不均衡に大きなペナルティが課されます。1つの柱が極端に低い都市は、他の柱が強くても引き下げられます。",
            citations: [1],
          },
          {
            id: "official-ampi-ja",
            title: "展開されたAMPI形式",
            formula: officialAmpiFormula,
            explanation: "公開スコアラーは、まず加重された柱의平均を計算し、次にその平均で割った加重された柱間分散ペナルティを引きます。これが、1次元的な都市プロファイルが高スコアを得るのを困難にする数学的ステップです。",
            citations: [1],
          },
          {
            id: "disposable-income-ja",
            title: "税調整済みPPP可処分所得",
            formula: "DI_ppp(c) = ((GrossIncome(c) x (1 - TaxRate(country(c)))) - Rent(c) - Utilities(c) - Transit(c) - Internet(c) - Food(c)) / PPPPrivateConsumptionFactor(country(c))",
            explanation: "これが中心的な生活空間の項です。税金と必須コストを除いた後に残るポストタックス所得を、PPP民間消費係数を通じて比較可能な購買力空間に、明示的に1回変換します。",
            citations: [2, 7],
          },
        ],
      },
      {
        id: "normalization-ja",
        eyebrow: "指標のメカニズム",
        title: "正規化とカバレッジロジック",
        summary: "生の都市指標は、スコアリングの前に方向性と欠損値が明示的に処理された後にのみ集計できます。",
        equations: [
          {
            id: "metric-normalization-ja",
            title: "ウィンザー化された指標スコア",
            formula: "If dir(m) = positive:\n  s_m(c) = 100 x clamp((winsor(x_m(c)) - P5_m) / (P95_m - P5_m), 0, 1)\nIf dir(m) = negative:\n  s_m(c) = 100 x clamp((P95_m - winsor(x_m(c))) / (P95_m - P5_m), 0, 1)",
            explanation: "公開モデルは、P5/P95ウィンザー化を使用し、0〜100に正規化します。有害な指標は分子を反転させるため、正規化されたスコアが高いほど、常に良好な都市結果を意味します。",
            citations: [1],
          },
          {
            id: "coverage-score-ja",
            title: "加重カバレッジ",
            formula: "Cov_p(c) = Sum over metrics m of alpha_(p,m) x cov_m(c) / Sum over metrics m of alpha_(p,m)\nCov(c) = (25 Cov_pressure + 22 Cov_viability + 18 Cov_capability + 15 Cov_community + 20 Cov_creative) / 100",
            explanation: "カバレッジは、生のフィールド数ではなく、公開された指標の重要性によって加重されます。直接指標は1または0に貢献し、複合指標は観察されたコンポーネント重量のシェアに貢献します。",
            citations: [1, 14, 15],
          },
        ],
      },
      {
        id: "subscores-ja",
        eyebrow: "公開サブスコア方程式",
        title: "読者に見える形で残るサブスコア",
        summary: "以下の目に見える柱方程式は、公開スコアで使用されるワークブック構造と一致しています。",
        equations: [
          {
            id: "growth-pillar-ja",
            title: "Growthの柱",
            formula: growthPillarFormula,
            explanation: "公開集計は、生活圧力のバンドルを直接スコア化します。経済成長の勢いはスコアカードに表示されますが、これは診断用の行であり、現在の集計式のスコア項ではありません。",
            citations: [1, 2, 3, 7],
          },
          {
            id: "community-tolerance-ja",
            title: "Tolerance composite",
            formula: toleranceCompositeFormula,
            explanation: "コミュニティは、単一のプロキシではなく、スコア化された開放性の複合指標を使用します。都市のヘイトクライムデータが薄い場合、3番目の項は国レベルの市民的自由プロキシにフォールバックします。",
            citations: [1, 14, 16, 35],
          },
          {
            id: "business-growth-ja",
            title: "Economic vitality composite",
            formula: economicVitalityFormula,
            explanation: "マクロな文脈は重要だが、都市レベルの証拠を覆い隠さないように、宣言された複合指標内に制限されます。出生率と気候は、読者向けの目に見える診断にとどまり、集計には直接入力されません。",
            citations: [2, 10, 16],
          },
        ],
      },
    ],
  },
  glossarySection: {
    eyebrow: "記号用語集",
    title: "すべての記号の意味",
    summary: "表記法は意図的に簡潔にされています。外部の読者がスコアを再現したりワークシートを監査したりできるように、各記号は一度だけ定義されています。",
    symbols: [
      { symbol: "c", definition: "都市または機能的都市地域", explanation: "スコア化される都市の単位。" },
      { symbol: "m", definition: "指標インデックス", explanation: "1つの公開された柱の中にあるスコア化された指標項目。" },
      { symbol: "k", definition: "入力チャネル", explanation: "直接または複合指標の内部で使用される生の入力値。" },
      { symbol: "p", definition: "柱インデックス", explanation: "5つの公開された柱のいずれか。" },
      { symbol: "x_k(c)", definition: "生の入力値", explanation: "ウィンザー化前における、都市cの入力チャネルkの観測値。" },
      { symbol: "winsor(.)", definition: "ウィンザー化演算子", explanation: "スコアリングの前に極端な値をP5/P95の範囲にクランプします。" },
      { symbol: "P5_k, P95_k", definition: "固定パーセンタイル境界", explanation: "入力kに対する正規化の下限および上限境界。" },
      { symbol: "s_k(c)", definition: "正規化された入力スコア", explanation: "ウィンザー化と方向調整後の0〜100のスコア。" },
      { symbol: "M_m(c)", definition: "複合指標スコア", explanation: "複合指標mに対する、正規化されたコンポーネントスコアの加重平均。" },
      { symbol: "alpha_(p,m)", definition: "柱の中の指標のウェイト", explanation: "柱pにおける指標mの強さ。" },
      { symbol: "cov_m(c)", definition: "指標のカバレッジ", explanation: "指標に必要な証拠の観察された割合（0〜1）。" },
      { symbol: "Cov_p(c)", definition: "柱のカバレッジ", explanation: "指標ウェイトで重み付けした後の、柱pのカバレッジスコア。" },
      { symbol: "Cov(c)", definition: "全体的な加重カバレッジ", explanation: "5つの柱カバレッジスコアの加重平均。" },
      { symbol: "w_p", definition: "公開された柱のウェイト", explanation: "全体のAMPIステップで柱pに適用される固定ウェイト。" },
      { symbol: "mu(c)", definition: "加重柱平均", explanation: "AMPIペナルティを課す前の、5つの柱スコアの加重平均。" },
      { symbol: "var(c)", definition: "加重柱分散", explanation: "不均衡をペナルティ化するために使用される柱間分散。" },
      { symbol: "AMPI(c)", definition: "調整マッツィオッタ・パレート指数", explanation: "カバレッジペナルティ前の、分散ペナルティ付き全体複合スコア。" },
      { symbol: "penalty(c)", definition: "カバレッジペナルティ", explanation: "カバレッジグレードに応じて課される0、5、または15ポイントの減点。" },
      { symbol: "DI_ppp(c)", definition: "PPP可処分所得", explanation: "手取り所得から必須支出を差し引き、PPP消費係数で調整した生活実態指標。" },
    ],
  },
  workedExampleSection: {
    eyebrow: "計算の具体例",
    title: "公開データの算出ウォークスルー",
    summary: "この例は、実際の公開データ行を使用しているため、装飾的ではなく監査可能な算術となっています。",
    example: {
      city: `${workedExampleDisplayName} の公開行`,
      note: "以下の数値は、`publishedRankingData.json` のスナップショットから取得され、公開スコアカードと同じように四捨五入されています。",
      inputs: [
        { label: "DI_ppp raw", value: workedExampleDiRaw, note: `${workedExampleDisplayName} の公開された生の可処分所得入力値` },
        { label: "Personal safety raw", value: workedExample?.safety?.raw != null ? String(workedExample.safety.raw) : "—", note: "負の方向性正規化の例で使用された生の殺人/危害入力値" },
        { label: "Pressure pillar", value: formatOneDecimal(workedExample?.pillarScores?.pressure ?? undefined), note: "観測された指標にわたる加重平均後の公開された柱スコア" },
        { label: "Viability pillar", value: formatOneDecimal(workedExample?.pillarScores?.viability ?? undefined), note: "公開された柱スコア" },
        { label: "Capability pillar", value: formatOneDecimal(workedExample?.pillarScores?.capability ?? undefined), note: "公開された柱スコア" },
        { label: "Community pillar", value: formatOneDecimal(workedExample?.pillarScores?.community ?? undefined), note: "公開された柱スコア" },
        { label: "Creative pillar", value: formatOneDecimal(workedExample?.pillarScores?.creative ?? undefined), note: "公開された柱スコア" },
      ],
      steps: [
        {
          title: "負の方向性正規化の例",
          formula: workedExampleSafetyFormula,
          result: `SafetyScore = ${formatOneDecimal(workedExample?.safety?.scoreRounded ?? undefined)}`,
          explanation: `${workedExampleDisplayName} の個人安全入力は負の方向であるため、分子が反転します。ここでのP5/P95境界値は、公開スコアラーで使用されている固定の \`normStats\` スナップショットから取得されます。`,
        },
        {
          title: "Growthの柱の加重平均",
          formula: workedExamplePressureFormula,
          result: `Growth = ${formatOneDecimal(workedExample?.pressure?.scoreRounded ?? undefined)}`,
          explanation: "観測された指標のみが分母に入ります。経済成長モメンタムはスコアカードに表示されますが、現在の集計式には入りません。",
        },
        {
          title: "柱間の加重平均と分散",
          formula: workedExampleMeanFormula,
          result: `mu = ${formatThreeDecimals(workedExample?.overall?.weightedMeanExact ?? undefined)}, var = ${formatTwoDecimals(workedExample?.overall?.weightedVarianceExact ?? undefined)}`,
          explanation: `これが柱間の不均衡ペナルティのステップです。もし ${workedExampleDisplayName} が同じ加重平均を持ちながら、より均衡な柱を持っていたなら、最終的なスコアは高くなっていたでしょう。`,
        },
        {
          title: "AMPIと最終公開スコア",
          formula: workedExampleAmpiFormula,
          result: `SLIC = ${formatOneDecimal(workedExample?.overall?.slicScoreRounded ?? undefined)}`,
          explanation: `AMPIは不均衡にペナルティを課すため、最終スコアは柱平均を下回ります。${workedExampleDisplayName} はグレード ${workedExample?.overall?.coverageGrade ?? "—"} を保持しているため、カバレッジによる減点はありません。`,
        },
      ],
      finalScore: formatOneDecimal(workedExample?.overall?.slicScoreRounded ?? undefined),
      conclusion: "この例が示す核心は方法論的な誠実さです。ViabilityとCapabilityが極めて強力であっても、Communityの弱点をかき消すことはできません。分散ペナルティは、SLICが1次元的な都市の強みを、あたかも他の分野と交換可能であるかのように評価することを防ぎます。",
    },
  },
  modelSection: {
    eyebrow: "手法の境界",
    title: "1つの公開モデル、診断は分離",
    summary: "公開スコアは、宣言された1つのAMPIモデルから算出されます。診断指標は表示される場合がありますが、公開される集計値を静かに変更することはありません。",
    families: [
      {
        id: "weighted-ja",
        title: "公式公開モデル",
        formula: officialSlicFormula,
        role: "公開スコア",
        explanation: "これが唯一の公開スコアリングエンジンです：固定ウェイト、ウィンザー化正規化、加重柱平均、柱間の加重AMPI、および明示的なカバレッジペナルティ。",
      },
      {
        id: "diagnostics-ja",
        title: "内部診断",
        formula: "Diagnostics(c) do not modify SLIC(c)",
        role: "非スコアリングチェック",
        explanation: "経済成長の勢い、気候と日照の住みやすさ、出生率の楽観性は、スコアカードに表示されたままにできますが、総合スコアには直接入力されません。表示と重みは異なります。",
      },
      {
        id: "profile-match-ja",
        title: "探索的プロファイルマッチャー",
        formula: "Match(c,u) = similarity(profile(c), preference(u))",
        role: "探索のみ",
        explanation: "蜘蛛の巣（スパイダーチャート）インタラクションは公開されたランキングではありません。都市の5つの柱の分布形状と、ユーザーが宣言した設定を比較するものです。",
      },
    ],
  },
  countryContextSection: {
    eyebrow: "国別コンテキスト項目",
    title: "マクロな强さは重要だが、支配的ではない",
    summary: "1人当たりGDP、成長、格差、PPP、税率はすべて重要ですが、SLICには決定要因ではなく、規律あるコンテキストまたは調整項目として入力されます。",
  },
  weightChartLabel: "公式スコアの",
  pillarsSection: {
    eyebrow: "公式の柱",
    title: "スコアの背景にある5つの公開された柱",
    summary: "以下の各柱は、公開スコアで使用されるワークブックのウェイトと指標構造に一致しています。",
  },
  pillars: [
    {
      id: "pressure",
      name: "Growth",
      weight: 25,
      thesis: "経済活力は都市の軌跡を決定しますが、それに伴う住宅費、過度な労働、債務、重い心理的負担といった生活圧力は、生活空間として誠実に評価されるべきです。",
      justification: "この柱は名声に隠された実質的な生活圧力を測定し、可処分所得/生活空間をスコアの核心に据えます。経済成長は補助指標として表示されます。",
      citations: [2, 3, 7],
      metrics: [
        { name: "税調整済みPPP可処分所得", weight: 9, description: "手取り所得から必須支出を差し引き、PPP消費係数で調整した生活実質購買力指標。", inputs: ["総所得", "税率", "家賃", "公共料金", "インターネット費用", "交通費", "食費", "PPP因子"] },
        { name: "住宅価格圧力", weight: 5, description: "都市市場における平方フィートあたりの住宅購入価格。高い住宅価格は地域居住者の資産形成と生活構築を阻害します。", inputs: ["平方フィート当たり米ドル", "都市市場購入価格"] },
        { name: "家庭債務負担", weight: 4, description: "可処分所得に対する負債総量 또는 最適な代理指標の比率。", inputs: ["家計債務プロキシ"] },
        { name: "労働時間圧力", weight: 4, description: "週平均労働時間および過重労働の割合。長時間労働が深刻であるほど、スコアは減点されます。", inputs: ["週労働時間", "過労割合"] },
        { name: "自殺と極度の心理的ストレス", weight: 3, description: "都市の深刻な心理的疲弊を示す公衆衛生の代理シグナル。", inputs: ["年齢調整自殺率"] },
        { name: "経済的ストレス（ハンケ悲惨指数）", weight: 2, description: "2025年ハンケ年間悲惨指数：(2×失業率) + インフレ率 + 銀行貸出金利 - 実質1人当たりGDP成長率。国レベルのデータ。低いほどストレスが少ないことを示します。", inputs: ["失業率", "CPIインフレ率", "銀行貸出金利", "実質1人当たりGDP成長率"] },
      ],
    },
    {
      id: "viability",
      name: "Viability",
      weight: 22,
      thesis: "都市の日常生活はより安全で、快適に呼吸して移動でき、公共サービスが安定的でありながら強制力を持たないべきです。",
      justification: "この柱は展示用のスマートシティではなく、住民が体験する実際の結果を評価します。気候条件は診断表示されますが、柱のスコアは以下の指標のみで構成されます。",
      citations: [3, 5, 11, 13, 17],
      metrics: [
        { name: "個人安全", weight: 5, description: "凶悪犯罪発生率、訪問者被害率、および夜間の安全感を評価します。", inputs: ["殺人", "重大暴力犯罪", "被害率", "夜間安全プロキシ"] },
        { name: "交通アクセスと通勤負担", weight: 5, description: "公共交通網の網羅性と、平均通勤所要時間です。（現在データ不足により全都市で一時利用停止中です）", inputs: ["GTFS交通データ", "通勤時間", "カバレッジ"] },
        { name: "清潔な空気", weight: 4, description: "PM2.5の年間平均濃度および基準値超過日数をCAMSとOpenAQデータを用いてスコア化します。", inputs: ["PM2.5", "環境基準超過数", "エアロゾルコンテキスト"] },
        { name: "給排水・衛生とインフラ信頼性", weight: 4, description: "安全な水と衛生設備へのアクセス、および停電・断水の頻度と遵守状況。", inputs: ["WASH給排水アクセス", "供給断続・停電", "安全規則遵守"] },
        { name: "デジタルインフラ", weight: 4, description: "固定ブロードバンド品質、価格の手頃さ、および光回線の普及度。", inputs: ["固定ブロードバンド", "価格手頃さ", "回線速度性能"] },
        { name: "気候と日照の快適性", weight: 7, description: "年間日照時間、気温の快適性、および極端な気象災害への遭遇リスクを統合した指標。", inputs: ["日照時間", "気温の快適性", "気象災害強度"] },
      ],
    },
    {
      id: "capability",
      name: "Capability",
      weight: 18,
      thesis: "本格的な都市は、優れたヘルスケア、質の高い教育、および社会進出への公正な道筋を保証します。",
      justification: "単に施設数を誇るのではなく、実際のサービス品質と実質的なアクセス確保を評価します。",
      citations: [3, 6, 8, 9, 14, 15],
      metrics: [
        { name: "医療の質", weight: 8, description: "回避可能な死亡率、受け入れ能力、および効果的な医療アクセスを測定します。", inputs: ["回避可能な死亡率", "医療服务評判", "医療インフラ収容力"] },
        { name: "教育の质", weight: 6, description: "PISA学力到達度、学修修了率、および職業訓練などのスキル供給パイプライン。", inputs: ["PISA学術成績", "UIS教育指標", "学業修了率", "技能人材供給力"] },
        { name: "機会均等と分配の公正", weight: 4, description: "ジェンダー格差、若年NEET（非就労非就学）率、およびジニ係数差を統合した指標です。", inputs: ["ジェンダー格差情報", "若年ニート(NEET)比率", "ジニ係数", "雇用格差"] },
      ],
    },
    {
      id: "community",
      name: "Community",
      weight: 15,
      thesis: "都市は単なる仕事場ではありません。温かい歓迎、多様性への寛容、文化的魅力、および帰属感こそが人を呼び寄せます。",
      justification: "SLICは、名声ではなく実際の社会的な包容力を測定し、評価に反映します。出生率は補助的な文脈指標です。",
      citations: [1, 14, 16],
      metrics: [
        { name: "文化的・公共的生活の活力", weight: 7, description: "サードプレイス（第3の居場所）、歴史的資産の保全、イベント、および混雑度で調整した観光誘客力。", inputs: ["娯楽施設数", "イベント開催数", "公共関心度", "観光客流入規模"] },
        { name: "ホスピタリティと帰属感", weight: 6, description: "純人口流入、居住者定着度、および外国語サポートインフラの統合指標。", inputs: ["純移動流入", "評判監査および実証調査", "多言語サポートインフラ"] },
        { name: "包容性と多様性", weight: 4, description: "LGBTQ+法的権利、社会の差別的指標、および雇用機会均等と移動の自由です。", inputs: ["性的少数者法的権利", "差別代理指標", "市場参入開放性"] },
        { name: "社会的楽観（出生率基準）", weight: 2, description: "世界銀行の合計特殊出生率（TFR）データを社会の将来的な信頼度として反映しますが、主要な評価決定力は持ちません。", inputs: ["世界銀行合計特殊出生率"] },
        { name: "市民の自由と尊厳", weight: 4, description: "HRMIエンパワーメントスコア(0.4)、Freedom House自由度(0.3)、V-Dem自由民主主義指数(0.3)を統合した指標です。", inputs: ["HRMIエンパワーメントスコア", "Freedom House FIW", "V-Dem LDI"] },
      ],
    },
    {
      id: "creative",
      name: "Creative",
      weight: 20,
      thesis: "都市は苦痛を取り除くだけでなく、住民の挑戦心、発明、生産的エネルギー、そしてビジネス機会を育むべきです。",
      justification: "この柱は、快適さが停滞を招くのを防ぎ、知識経済の創出力と参入の容易さを評価します。観光や娯楽は「Community」に分類されます。",
      citations: [2, 10, 16],
      metrics: [
        { name: "起業家精神の活力", weight: 6, description: "新規創業率、スタートアップ企業設立の速度と集積化スピード。", inputs: ["新規企業密度", "新设法人創出", "起業活動規模"] },
        { name: "イノベーションと研究の活発さ", weight: 5, description: "特許出願件数、研究開発費（R&D）支出額、および主要学術研究機関の厚み。", inputs: ["特許出願", "R&D支出", "研究学術機関"] },
        { name: "经济活力と生産的コンテキスト", weight: 5, description: "投资诱致、生产性上昇、および都市のマクロ経済的成長の安全軌道。", inputs: ["投資誘致シグナル", "1人当たりGDP(PPP)", "GDP成長率"] },
        { name: "行政・投資摩擦", weight: 4, description: "许认可手续的手间、行政的便利性、および规则的一贯性に起因する投资妨害度。", inputs: ["行政処理遅延", "許認可発行負担", "規則一貫性"] },
      ],
    },
  ],
  protocolSection: {
    eyebrow: "ランキングプロトコル",
    title: "都市の参入、維持、公開の流れ",
    summary: "ランキングは、データの欠損と規模を誠実に扱う必要があります。有名な都市が自動的に含まれるわけではなく、データの薄い都市が偽りの精度を持つこともありません。",
  },
  rules: [
    {
      title: "行政境界ではなく、機能的都市地域（FUA）を採用",
      body: "SLICは、任意の地方自治体の境界ではなく、実際の労働市場やサービス提供範囲に基づいて都市を定義し、測定します。",
      citations: [12],
    },
    {
      title: "固定された公式ウェイト",
      body: "公開リーダーボードは、1つの宣言されたウェイト体系と部門間のAMPIペナルティを使用します。ユーザーによる変更は探索用のみで、公式ランクには影響しません。",
      citations: [1],
    },
    {
      title: "ランキング前のカバレッジゲート",
      body: "加重カバレッジ率が一定の基準を満たした都市のみがランク付けされます。基準値に達しない都市はウォッチリストにとどまります。",
      citations: [1, 14, 15],
    },
    {
      title: "安全性は監視ではなく結果で評価",
      body: "カメラの台数やスマートシティのデモンストレーション自体は評価されません。実際の被害の少なさと住民の日々の信頼感が評価されます。",
      citations: [1, 3],
    },
    {
      title: "寛容性は観察された都市効果で評価",
      body: "SLICは特定の宗教や属性を直接スコア化しません。住民が日常業務や経済活動に低摩擦かつ対等に参加できる自由があるかを測定します。",
      citations: [1, 14],
    },
    {
      title: "観光需要は文脈であり、自動的な加算ではない",
      body: "訪問者の流入は、混雑、安全性、環境、住民の生活空間への負荷をチェックし、それらをクリアした場合にのみ文化的需要のシグナルとして扱われます。バンコクの旅行コストに関する証拠は、観光魅力が低価格の旅行コストと両立していることを証明しますが、これ自体は直接の加点要素ではありません。",
      citations: [1, 36, 37],
    },
    {
      title: "V3.3: 純スコア順位と公開階層の分離",
      body: japaneseTierProtocolRule,
      citations: [],
    },
    {
      title: "V3.3: 階層プロトコルにおけるシンガポールとバンコクの評価",
      body: japaneseSingaporeRule,
      citations: [],
    },
    {
      title: "V3.2: 紛争地域のウォッチリスト",
      body: "シェルター警報の常態化や民間インフラへの攻撃が発生しているアクティブな紛争地域内の都市は、通常の平和な都市と一律に比較できないため、順位付けから除外され、ウォッチリストに配置されます。都市カードは維持されますが、持続的な停戦と住民の帰還によって環境が正常化した時点で順位に復帰します。",
      citations: [],
    },
    {
      title: "V3.1: 住宅価格天井の拡大",
      body: "住宅負担のウィンザー化天井を実際の市場購入価格へ拡大したため、高コスト都市間の住宅コストの差がそのまま生活圧力（Growth）のスコアを左右するようになりました。",
      citations: [],
    },
    {
      title: "目に見える診断指標は隠されたウェイトではない",
      body: "経済成長率、気候/日照、出生率などの指標はスコアカードに表示されますが、公式なスコアリングには直接的な影響を与えません。手法は公開コンテキストとスコア化された証拠を区別します。",
      citations: [],
    },
    {
      title: "複合指標の透明性の維持",
      body: "機会均等、包容性、经济活力などの指標はブラックボックスではなく、構成ウェイトを宣言し、欠損がある場合は観測データのみで再調整されます。",
      citations: [],
    },
    {
      title: "V3: PPP変換は明確に1回のみ適用",
      body: "SLICは、可処分所得メトリックの内部で、PPP民間消費係数を1回だけ適用して他国間の手取り購入価値を比較可能にしています。他の箇所に隠れた重複調整はありません。",
      citations: [],
    },
  ],
  sourceSection: {
    eyebrow: "ソース階層",
    title: "モデルが優先的に信頼するデータ",
    summary: "以下のデータラダーは、情報源の距離を示します。都市レベルのデータは国家代替指標に優先し、監査済みプロキシは出所のあいまいな数値に優先します。",
  },
  sourceTiers: japaneseSourceTiers,
  worksheetSection: {
    eyebrow: "スコアリングワークシート",
    title: "ランキングを支える都市ごとのデータテーブル",
    summary: "都市リストが確定すると、これらの列が埋められ、モデルは柱のスコア、最終SLICスコア、およびカバレッジグレードを計算します。",
  },
  worksheetColumns,
  referencesSection: {
    eyebrow: "参考文献",
    title: "このフレームワークを裏付ける文献ライブラリ",
    summary: "方法论は、内部ベンチマークメモ、および公式モデルやワークシートの算術的基礎を規定する公式の文書を引用しています。",
  },
  references: methodologyReferences,
};
